Host = "0.0.0.0"
Port = "2222"
ServerName = "isle.chat"
AdminUsername = "admin"
BotUsername = "islebot"
GlobalBanner = "                              ⢶⣄              ⠉⠛⢓⣶⣦⢿⣦⣴⡖⠛⠋          ⠚⠋⠁⢠⣿⠃⠉⠉⠛⠒⠂  isle.chat⢀⣾⠇        v0.0.0   ⣼⡟         #global ⢰⣿⠁          ⢀⣠⣤⣤⣴⣶⣶⣾⣯⣤⣤⣤⣤⣤⣀⣀   ⠰⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠿⠦                     "
AnnouncementChannel = "news"
DefaultBanner = "                              ⢶⣄              ⠉⠛⢓⣶⣦⢿⣦⣴⡖⠛⠋          ⠚⠋⠁⢠⣿⠃⠉⠉⠛⠒⠂  isle.chat⢀⣾⠇        v0.0.0   ⣼⡟         default ⢰⣿⠁          ⢀⣠⣤⣤⣴⣶⣶⣾⣯⣤⣤⣤⣤⣤⣀⣀   ⠰⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠿⠦                     "
WelcomeMessage = "A new user joined for the first time! Welcome @%s. Run /help for information"
FilterPublicMessages = false
RegistrationHeader = "isle.chat registration   "
DatabaseMode = "postgres"
PostgresHost = "postgres"
PostgresUser = "islechat"
PostgresPassword = "123456789"
PostgresDBName = "islechat"
PostgresPort = "5432"
PostgresSSL = "disable"
