version: '3.8'

services:
  islechat:
    image: ashfn0/islechat
    tty: true
    stdin_open: true
    ports:
      - "2222:2222"
    environment:
      LOG_LEVEL: info
      CLICOLOR_FORCE: 1
      COLORTERM: truecolor
      TERM: xterm-256color
    # Add this if you are using a port below 1024
    # cap_add:
    #   - NET_BIND_SERVICE
    tmpfs:
      - /tmp
    volumes:
          - ./ssh_keys/id_ed25519:/home/islechat/app/.ssh/id_ed25519:ro   # <-- ADD THIS LINE
          - ./config.toml:/home/islechat/config.toml